### ISSUE TITLE
Genders

### ISSUE THREAD

**Issue by GeorgH93** [GeorgH93/MarriageMaster#45]
Players should be able to define a gender for their character.

### ToDo:

- [ ] Allow players to chose a gender from a list of available genders

- [ ] Give option to allow players to define their own gender (if enabled by the admin)

- [ ] Give admins the option to configure the available genders

- [ ] Give option to allow players to change their gender

  - [ ] Fees for gender changes

- [ ] Allow admins to restrict marriages based on gender

**Expose gender through:**

  - [ ] API

  - [ ] Placeholders

  - [ ] Prefix

**Comment by AngellitoX** [comment]
Hello! Is this already implemented?

**Comment by GeorgH93** [comment]
Will be included in the next update (v2.3). Had to push v2.2 a bit earlier than expected because of the MC 1.16 release.
